title: Data Squadron || Data engineering, analytics and visualization experts 
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/blog/:year/:month/:day/:title'
palette: blue
header:
  title: Data Squadron
  logo_img: images/logo.png
  has_nav: true
  menu:
    actions:
      - label: Contact Us
        url: /contact
footer:
  logo_img: images/logo_alt.png
  tagline: Data engineering, analytics and visualization experts
  has_nav: false
  nav_title: Company
  has_social: false
  social_title: Community
  has_subscribe: true
  subscribe_title: Contact
  subscribe_content: Leave your email and we'll get back to you.
  content: '&copy; 2019 Data Squadron. All rights reserved.'
  links:
    - text: Handcrafted by BlackOps.one
      url: 'https://www.blackops.one'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
